import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import './globals.css';
import styles from './layout.module.css';
import { Logo, MiniLogo } from './_component/Logo';
import NavMenu from './_component/NavMenu';
import Link from 'next/link';
import NavMenuHorizontal from './_component/NavMenuHorizontal';
import TopButton from './_component/TopButton';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const my = {
  name: '김현수',
  photo: '/image/navi.jpeg',
};

const rank = {
  theme: '층간소음',
  location: '홍대',
  store: '제로월드 홍대점',
};

const temp = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0];

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className={styles.container}>
          <section className={styles.leftSection}>
            <div className={styles.leftSectionFixed}>
              <Link href="/home">
                <div className={styles.logo}>
                  <Logo width={150} height={100} />
                </div>
                <div className={styles.miniLogo}>
                  <MiniLogo width={50} height={50} />
                </div>
              </Link>
              <nav>
                <ul style={{ listStyle: 'none', paddingLeft: '0' }}>
                  <NavMenu />
                </ul>
              </nav>
            </div>
          </section>
          <section className={styles.middleSection}>{children}</section>
          <section className={styles.rightSection}>
            <aside>
              <header>
                <div className={styles.rightSectionHeader}>일간 차트</div>
              </header>
              {temp.map((_, idx) => (
                <Link href={'/theme/info'}>
                  <div className={styles.chart}>
                    <div className={styles.chartNumber}>{idx + 1}</div>
                    <div>
                      <div>{rank.theme}</div>
                      <div className={styles.chartLocation}>{`${rank.location} | ${rank.store}`}</div>
                    </div>
                  </div>
                </Link>
              ))}
            </aside>
            <footer className={styles.rightFooter}></footer>
          </section>
          <section className={styles.topSection}>{children}</section>
          <section className={styles.bottomSection}>
            <NavMenuHorizontal />
          </section>
          <TopButton />
          {modal}
        </div>
      </body>
    </html>
  );
}
